name: Simple ZIP Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create deployment package
      run: |
        zip -r deployment.zip web_agent.py requirements.txt templates/ startup.txt
    
    - name: Deploy to Azure using REST API
      run: |
        curl -X POST \
          -H "Content-Type: application/zip" \
          -u '${{ secrets.AZURE_DEPLOYMENT_USERNAME }}:${{ secrets.AZURE_DEPLOYMENT_PASSWORD }}' \
          --data-binary @deployment.zip \
          'https://agentinboxiq.scm.azurewebsites.net/api/zipdeploy'
